/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tndcjzfmaeiynjuhtkoa"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZGNqemZtYWVpeW5qdWh0a29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxOTg5MTgsImV4cCI6MjA3NDc3NDkxOH0.BUJSfQ-UzrWr0tb38TecGP99jvv4oAgKAGTkWQsBh-0"